services:
  - type: web
    name: smart-agri-predict-backend
    runtime: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
